services:
  web:
    build: .
    environment:
      "REDIS_CONNECTION_STRING": "redis://host.docker.internal:6379/10"
    ports:
      - "8080:8080"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"